### ISSUE TITLE
Provision Rik an AWS server

### ISSUE THREAD

**Issue by tdooner** [openoakland/infra#1]
Now that we have an AWS account, we need to provision @rbelew a server for oakcrime.org.

The requirements are:
* 4 GB RAM
* nothing else, rik is going to do everything

I promised him a `t2.medium`.

Rik's SSH key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDANcxjoBW5sHZWTfuRDZDMBAQabaR2iCMYwrc1NizljZGTIWebeTsJeMGcAxjHCWyVUtiub0zRXc5GQhqdxHlQNnqRTBhlluO+XZg61rHtFp7yc080eot0wU1YTCdwf/oJXBnPc31Q9vlZnwZuz88mI9s3z/JE5J/bVRGHbsKFgDzUWacvwuZRlYftI4HiGJUgISf501/55jiyvgCB+qfGggqszhD3LTmzOW6JlxBfasvY+eL9NWjAitjFv+D6U4HVVO6JEhcd54LtpNFvkxEet0ldKujQ2FUI6VapW4APOwvw9x0jsZ41AiQF90NbQaqegNRvkDoGsZS0cF2eKAHp
```

**Comment by tdooner** [comment]
I think this is fixed by https://github.com/openoakland/infra/commit/b06f53a29e3504373b3d3ca4da7b9098d3345071 but I'm going to wait to hear back from Rik.

**Comment by rbelew** [comment]
hey Tom,  summer is good and i'm getting to do stuff!  like make this transfer happen. 
but while i am able to ssh and login via  with rsa keys, when i try to sudo i'm being prompted for a password?  haven't had this issue before, have you?
