### ISSUE TITLE
Find a place for Lovely Rita to host data

### ISSUE THREAD

**Issue by tdooner** [openoakland/infra#2]
We need to figure out where Lovely Rita can host its ~100 MB zipped CSV of data.

The DKAN thing comes to mind but it has some usability problems:
1. The "Register" page is broken (it doesn't let you register for an account unless you already have one)
2. The site doesn't use TLS
3. Is it even able to host this data?

cc @openoakland/lovely-rita

**Comment by adborden** [comment]
Is this still an issue?

**Comment by tdooner** [comment]
Nope, thanks for the bump. Closing.
